import AsyncStorage from '@react-native-async-storage/async-storage';
import { GymUser } from './types';

const USERS_KEY = 'zyntra_gym_users';

export const SEED_PARTICIPANTS: GymUser[] = [
  {
    id: 'user_chethiya',
    name: 'Chethiya',
    age: 21,
    heightCm: 178,
    weightKg: 75,
    role: 'Volleyball Player (UoM)',
    createdAt: '2026-09-18T08:00:00.000Z',
    baseline: {
      hrvRmssd: 54.2,
      tempC: 33.4,
      rtMedianMs: 215,
      capturedAt: '2026-09-18T08:30:00.000Z',
      isAutoGenerated: false,
    },
    testResults: [
      {
        id: 'test_chethiya_1',
        timestamp: '2026-09-20T10:15:00.000Z',
        cleared: false,
        hrvDataValid: true,
        hrvPass: true,
        tempPass: true,
        rtPass: false,
        rmssd: 51.8,
        tempDeltaC: 0.4,
        medianRtMs: 495,
        minutesToClearance: 5,
      },
    ],
  },
  {
    id: 'user_bhanu',
    name: 'Bhanu',
    age: 24,
    heightCm: 172,
    weightKg: 80,
    role: 'Volleyball Player (UoM)',
    createdAt: '2026-09-18T08:30:00.000Z',
    baseline: {
      hrvRmssd: 58.0,
      tempC: 33.2,
      rtMedianMs: 228,
      capturedAt: '2026-09-18T09:00:00.000Z',
      isAutoGenerated: false,
    },
    testResults: [
      {
        id: 'test_bhanu_1',
        timestamp: '2026-09-20T10:30:00.000Z',
        cleared: false,
        hrvDataValid: true,
        hrvPass: true,
        tempPass: true,
        rtPass: false,
        rmssd: 54.5,
        tempDeltaC: 0.4,
        medianRtMs: 482,
        minutesToClearance: 8,
      },
    ],
  },
  {
    id: 'user_usitha',
    name: 'Usitha',
    age: 23,
    heightCm: 175,
    weightKg: 70,
    role: 'Volleyball Player (UoM)',
    createdAt: '2026-09-18T09:00:00.000Z',
    baseline: {
      hrvRmssd: 62.5,
      tempC: 32.8,
      rtMedianMs: 210,
      capturedAt: '2026-09-18T09:30:00.000Z',
      isAutoGenerated: false,
    },
    testResults: [
      {
        id: 'test_usitha_1',
        timestamp: '2026-09-20T11:00:00.000Z',
        cleared: false,
        hrvDataValid: true,
        hrvPass: true,
        tempPass: true,
        rtPass: false,
        rmssd: 58.0,
        tempDeltaC: 0.3,
        medianRtMs: 465,
        minutesToClearance: 6,
      },
    ],
  },
  {
    id: 'user_thilanka',
    name: 'Thilanka',
    age: 24,
    heightCm: 180,
    weightKg: 78,
    role: 'Volleyball Player (UoM)',
    createdAt: '2026-09-18T09:30:00.000Z',
    baseline: {
      hrvRmssd: 66.0,
      tempC: 33.3,
      rtMedianMs: 235,
      capturedAt: '2026-09-18T10:00:00.000Z',
      isAutoGenerated: false,
    },
    testResults: [
      {
        id: 'test_thilanka_1',
        timestamp: '2026-09-20T11:30:00.000Z',
        cleared: false,
        hrvDataValid: true,
        hrvPass: false,
        tempPass: false,
        rtPass: true,
        rmssd: 48.3,
        tempDeltaC: 1.2,
        medianRtMs: 357,
        minutesToClearance: 12,
      },
    ],
  },
  {
    id: 'user_sehath',
    name: 'Sehath',
    age: 21,
    heightCm: 170,
    weightKg: 68,
    role: 'Volleyball Player (UoM)',
    createdAt: '2026-09-18T10:00:00.000Z',
    baseline: {
      hrvRmssd: 52.0,
      tempC: 33.5,
      rtMedianMs: 220,
      capturedAt: '2026-09-18T10:30:00.000Z',
      isAutoGenerated: false,
    },
    testResults: [
      {
        id: 'test_sehath_1',
        timestamp: '2026-09-20T12:00:00.000Z',
        cleared: false,
        hrvDataValid: true,
        hrvPass: true,
        tempPass: false,
        rtPass: false,
        rmssd: 48.8,
        tempDeltaC: 1.2,
        medianRtMs: 475,
        minutesToClearance: 10,
      },
    ],
  },
];

export async function loadUsers(): Promise<GymUser[]> {
  try {
    const raw = await AsyncStorage.getItem(USERS_KEY);
    if (!raw) {
      await saveUsers(SEED_PARTICIPANTS);
      return SEED_PARTICIPANTS;
    }
    const parsed = JSON.parse(raw) as GymUser[];
    if (parsed.length === 0) {
      await saveUsers(SEED_PARTICIPANTS);
      return SEED_PARTICIPANTS;
    }
    return parsed;
  } catch {
    return SEED_PARTICIPANTS;
  }
}

export async function saveUsers(users: GymUser[]): Promise<void> {
  try {
    await AsyncStorage.setItem(USERS_KEY, JSON.stringify(users));
  } catch (e) {
    console.error('[Storage] Failed to save users:', e);
  }
}

export async function addUser(user: GymUser): Promise<GymUser[]> {
  const users = await loadUsers();
  const updated = [...users, user];
  await saveUsers(updated);
  return updated;
}

export async function updateUser(updated: GymUser): Promise<GymUser[]> {
  const users = await loadUsers();
  const next = users.map(u => u.id === updated.id ? updated : u);
  await saveUsers(next);
  return next;
}

export async function deleteUser(id: string): Promise<GymUser[]> {
  const users = await loadUsers();
  const next = users.filter(u => u.id !== id);
  await saveUsers(next);
  return next;
}