import React, { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';
import { MqttZyntraLink } from './mqttLink';
import { loadUsers, updateUser, SEED_PARTICIPANTS } from './storage';
import { BaselineData, ClearanceResult, DeviceState, GymUser, LiveVitals, TestResult, ZyntraLink } from './types';

interface ZyntraStore {
  // MQTT state
  deviceState: DeviceState;
  vitals: LiveVitals | null;
  result: ClearanceResult | null;
  connecting: boolean;
  connect: (brokerUrl?: string) => Promise<void>;
  disconnect: () => Promise<void>;
  triggerBaseline: () => void;
  triggerBreak: () => void;
  acknowledgeResult: () => void;

  // User management
  users: GymUser[];
  selectedUser: GymUser | null;
  selectUser: (user: GymUser | null) => void;
  addUser: (user: Omit<GymUser, 'id' | 'createdAt' | 'baseline' | 'testResults'>) => Promise<void>;
  deleteUser: (id: string) => Promise<void>;

  // Baseline — saves to selected user
  saveBaseline: (data: BaselineData) => Promise<void>;

  // Test result — saves to selected user
  saveTestResult: (result: ClearanceResult) => Promise<void>;
}

const Ctx = createContext<ZyntraStore | null>(null);

export function getRtThresholdForAge(age: number = 24): number {
  if (age <= 25) return 450;
  if (age <= 35) return 480;
  if (age <= 45) return 500;
  if (age <= 55) return 530;
  if (age <= 65) return 580;
  return 650;
}

export function getTempMarginForAge(age: number = 24): number {
  if (age > 45) return 0.6;
  return 0.8;
}

export function calculateEstimateMinutes(
  rmssd: number | null,
  tempDeltaC: number | null,
  userBaseline: BaselineData | null,
  age: number = 24
): number {
  if (!userBaseline) return 0;
  let maxEstimate = 0;

  // 1. HRV Estimate: 3 min per 10% deficit (capped at 30 min)
  if (rmssd !== null && rmssd > 0 && userBaseline.hrvRmssd > 0) {
    const recoveryPct = rmssd / userBaseline.hrvRmssd;
    if (recoveryPct < 0.90) {
      const deficit = 0.90 - recoveryPct;
      let hrvEstimate = Math.round(deficit * 100 * 3);
      if (hrvEstimate > 30) hrvEstimate = 30;
      maxEstimate = Math.max(maxEstimate, hrvEstimate);
    }
  }

  // 2. Temp Estimate: 5 min per 0.5°C excess (capped at 20 min)
  const tempMargin = getTempMarginForAge(age);
  if (tempDeltaC !== null && tempDeltaC > tempMargin) {
    const excess = tempDeltaC - tempMargin;
    let tempEstimate = Math.round((excess / 0.5) * 5);
    if (tempEstimate > 20) tempEstimate = 20;
    maxEstimate = Math.max(maxEstimate, tempEstimate);
  }

  // 3. Realistic bounds: 5 min minimum if not cleared, 30 min max ceiling
  if (maxEstimate < 5) maxEstimate = 5;
  if (maxEstimate > 30) maxEstimate = 30;

  return maxEstimate;
}

export function generateDefaultBaseline(age: number = 24): BaselineData {
  let hrvMin = 38, hrvMax = 74;
  let tempMin = 32.0, tempMax = 35.0;
  let rtMin = 150, rtMax = 250;

  if (age <= 24) {
    hrvMin = 38; hrvMax = 74; tempMin = 32.0; tempMax = 35.0; rtMin = 150; rtMax = 250;
  } else if (age <= 29) {
    hrvMin = 35; hrvMax = 68; tempMin = 32.0; tempMax = 35.0; rtMin = 210; rtMax = 290;
  } else if (age <= 34) {
    hrvMin = 32; hrvMax = 63; tempMin = 32.0; tempMax = 35.0; rtMin = 210; rtMax = 290;
  } else if (age <= 39) {
    hrvMin = 28; hrvMax = 57; tempMin = 32.0; tempMax = 35.0; rtMin = 230; rtMax = 310;
  } else if (age <= 44) {
    hrvMin = 26; hrvMax = 51; tempMin = 32.0; tempMax = 35.0; rtMin = 230; rtMax = 310;
  } else if (age <= 49) {
    hrvMin = 21; hrvMax = 42; tempMin = 31.0; tempMax = 34.0; rtMin = 250; rtMax = 340;
  } else if (age <= 59) {
    hrvMin = 21; hrvMax = 42; tempMin = 31.0; tempMax = 34.0; rtMin = 275; rtMax = 375;
  } else {
    hrvMin = 16; hrvMax = 36; tempMin = 30.0; tempMax = 33.0; rtMin = 300; rtMax = 450;
  }

  const hrvRmssd = Number((hrvMin + Math.random() * (hrvMax - hrvMin)).toFixed(1));
  const tempC    = Number((tempMin + Math.random() * (tempMax - tempMin)).toFixed(1));
  const rtMedianMs = Math.floor(rtMin + Math.random() * (rtMax - rtMin));

  return {
    hrvRmssd,
    tempC,
    rtMedianMs,
    capturedAt: new Date().toISOString(),
    isAutoGenerated: true,
  };
}

export function ZyntraProvider({ children }: { children: React.ReactNode }) {
  const linkRef = useRef<ZyntraLink>(new MqttZyntraLink());

  const [deviceState, setDeviceState] = useState<DeviceState>('DISCONNECTED');
  const [vitals, setVitals] = useState<LiveVitals | null>(null);
  const [result, setResult] = useState<ClearanceResult | null>(null);
  const [connecting, setConnecting] = useState(false);
  const [users, setUsers] = useState<GymUser[]>([]);
  const [selectedUser, setSelectedUser] = useState<GymUser | null>(null);

  // Load users from storage and auto-connect MQTT on mount
  useEffect(() => {
    loadUsers().then(async loaded => {
      let hasChanges = false;

      const verifiedUsers = loaded.map(u => {
        // If participant matches one of our 5 gym seed participants, ensure they reflect the updated research baseline & test values
        const seedMatch = SEED_PARTICIPANTS.find(sp => sp.name.toLowerCase() === u.name.toLowerCase());
        if (seedMatch) {
          hasChanges = true;
          return seedMatch;
        }

        let userBaseline = u.baseline;
        if (!userBaseline) {
          hasChanges = true;
          userBaseline = generateDefaultBaseline(u.age);
        }

        const rtThreshold = getRtThresholdForAge(u.age);
        const tempMargin  = getTempMarginForAge(u.age);

        // Sanitize & re-evaluate test results according to participant age-dependent dynamic thresholds
        const sanitizedResults = u.testResults.map(r => {
          let tempDeltaC = r.tempDeltaC;
          if (tempDeltaC !== null && tempDeltaC > 5.0 && userBaseline) {
            hasChanges = true;
            tempDeltaC = Number(Math.abs(tempDeltaC - userBaseline.tempC).toFixed(1));
          }

          const hrvPass  = r.rmssd !== null && userBaseline ? r.rmssd >= 0.9 * userBaseline.hrvRmssd : r.hrvPass;
          const tempPass = tempDeltaC !== null ? tempDeltaC <= tempMargin : r.tempPass;
          const rtPass   = r.medianRtMs !== null ? r.medianRtMs < rtThreshold : r.rtPass;
          const cleared  = r.hrvDataValid && hrvPass && tempPass && rtPass;

          // Re-calculate minutesToClearance to range between 5 and 30 minutes for failed tests
          const minutesToClearance = cleared ? 0 : calculateEstimateMinutes(r.rmssd, tempDeltaC, userBaseline, u.age);

          if (r.tempDeltaC !== tempDeltaC || r.tempPass !== tempPass || r.rtPass !== rtPass || r.cleared !== cleared || r.minutesToClearance !== minutesToClearance) {
            hasChanges = true;
          }

          return {
            ...r,
            tempDeltaC,
            tempPass,
            rtPass,
            cleared,
            minutesToClearance,
          };
        });

        return {
          ...u,
          baseline: userBaseline,
          testResults: sanitizedResults,
        };
      });

      if (hasChanges) {
        await import('./storage').then(s => s.saveUsers(verifiedUsers));
      }

      setUsers(verifiedUsers);
      if (verifiedUsers.length > 0) setSelectedUser(verifiedUsers[0]);
    });

    // Auto-connect to MQTT on startup
    linkRef.current.connect().catch(err => {
      console.log('[ZyntraProvider] Auto-connect info:', err);
    });
  }, []);

  // Save baseline to currently selected user
  const saveBaseline = useCallback(async (data: BaselineData) => {
    if (!selectedUser) return;
    const updated: GymUser = {
      ...selectedUser,
      baseline: { ...data, isAutoGenerated: false },
    };
    const all = await updateUser(updated);
    setUsers(all);
    setSelectedUser(updated);
  }, [selectedUser]);

  // Save test result to currently selected user
  const saveTestResult = useCallback(async (r: ClearanceResult) => {
    if (!selectedUser) return;

    // Recalculate tempDeltaC for display if ESP32 sent raw temperature (> 5.0°C)
    // Preserves exact hardware collected verdict (cleared, tempPass, hrvPass, rtPass)
    let tempDeltaC = r.tempDeltaC;
    if (tempDeltaC !== null && selectedUser.baseline && tempDeltaC > 5.0) {
      const tempCurrent = tempDeltaC;
      tempDeltaC = Number(Math.abs(tempCurrent - selectedUser.baseline.tempC).toFixed(1));
    }

    const testResult: TestResult = {
      id: `test_${Date.now()}`,
      timestamp: new Date().toISOString(),
      cleared: r.cleared,
      hrvDataValid: r.hrvDataValid,
      hrvPass: r.hrvPass,
      tempPass: r.tempPass,
      rtPass: r.rtPass,
      rmssd: r.rmssd,
      tempDeltaC,
      medianRtMs: r.medianRtMs,
      minutesToClearance: r.minutesToClearance,
    };
    const updated: GymUser = {
      ...selectedUser,
      testResults: [testResult, ...selectedUser.testResults],
    };
    const all = await updateUser(updated);
    setUsers(all);
    setSelectedUser(updated);
  }, [selectedUser]);

  // Subscribe to MQTT hardware link events
  useEffect(() => {
    const link = linkRef.current;
    const offState    = link.onStateChange(setDeviceState);
    const offVitals   = link.onVitals(setVitals);
    const offBaseline = link.onBaseline(b => {
      saveBaseline(b);
    });
    const offResult   = link.onResult(r => {
      setResult(r);
      saveTestResult(r);
    });

    return () => {
      offState();
      offVitals();
      offBaseline();
      offResult();
    };
  }, [saveBaseline, saveTestResult]);

  const connect = useCallback(async (brokerUrl?: string) => {
    setConnecting(true);
    try {
      await linkRef.current.connect(brokerUrl);
    } catch (e) {
      console.warn('[ZyntraProvider] Connect error:', e);
    } finally {
      setConnecting(false);
    }
  }, []);

  const disconnect = useCallback(async () => {
    await linkRef.current.disconnect();
    setVitals(null);
    setResult(null);
  }, []);

  const triggerBaseline = useCallback(() => {
    linkRef.current.triggerBaseline();
  }, []);

  const triggerBreak = useCallback(() => {
    setResult(null);
    linkRef.current.triggerBreak(
      selectedUser?.baseline?.tempC,
      selectedUser?.baseline?.hrvRmssd,
      selectedUser?.age
    );
  }, [selectedUser]);

  const acknowledgeResult = useCallback(() => {
    linkRef.current.acknowledgeResult();
    setResult(null);
    setVitals(null);
  }, []);

  const selectUser = useCallback((user: GymUser | null) => {
    setSelectedUser(user);
  }, []);

  const addUser = useCallback(async (data: Omit<GymUser, 'id' | 'createdAt' | 'baseline' | 'testResults'>) => {
    const newUser: GymUser = {
      ...data,
      id: `user_${Date.now()}`,
      createdAt: new Date().toISOString(),
      baseline: generateDefaultBaseline(data.age),
      testResults: [],
    };
    const updated = await import('./storage').then(s => s.addUser(newUser));
    setUsers(updated);
    setSelectedUser(newUser);
  }, []);

  const deleteUser = useCallback(async (id: string) => {
    const updated = await import('./storage').then(s => s.deleteUser(id));
    setUsers(updated);
    if (selectedUser?.id === id) {
      setSelectedUser(updated.length > 0 ? updated[0] : null);
    }
  }, [selectedUser]);

  const store = useMemo<ZyntraStore>(() => ({
    deviceState, vitals, result, connecting,
    connect, disconnect, triggerBaseline, triggerBreak, acknowledgeResult,
    users, selectedUser, selectUser, addUser, deleteUser,
    saveBaseline, saveTestResult,
  }), [deviceState, vitals, result, connecting, connect, disconnect,
       triggerBaseline, triggerBreak, acknowledgeResult, users, selectedUser,
       selectUser, addUser, deleteUser, saveBaseline, saveTestResult]);

  return <Ctx.Provider value={store}>{children}</Ctx.Provider>;
}

export function useZyntra(): ZyntraStore {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error('useZyntra must be inside <ZyntraProvider>');
  return ctx;
}
